import Head from 'next/head'
import { gql } from "@apollo/client";
import client from '../../apollo-client';


export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 50),
    },
  };
}

export default function Home({ countries }:any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Countries Name and Codes</h1>
        {countries.map((country:any) => (
          <div key={country.code}>
            <p><b>Country Code: </b>{country.code}</p>
            <p><b>Country Name: </b>{country.name}</p>
            <br />
          </div>
        ))}

      </div>
    </>
  )
}


