import Head from 'next/head'
import { useQuery } from 'react-query'


export default function Home() {

  const { isLoading, error, data } = useQuery('repoData', () =>
    fetch('https://dummyjson.com/products/1').then(res =>
      res.json()
    )
  )

  if (isLoading) return 'Loading...'

  if (error) return `An error has occurred ${error}`

  return (
    <>
      <Head>
        <title>React Query Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{data.title}</h1>
        <img src={data.images[0]} />
        <p>{data.description}</p>
        <p>Price: ${data.price}</p>
        <p>Ratings: {data.rating}</p>
        <p>Stock: {data.stock} Pices</p>
      </div>
    </>
  )
}
